### ISSUE TITLE
Кэш не используется

### ISSUE THREAD

**Issue by TheMerret** [kaeeraa/ayugram-desktop#1]
1. Прописал репо в input'ах flake'a (где еще каналы). 
2. в nix.settings указал substituters + trusted keys
3. Добавил пакет в systemPackages
4. nixos-rebuild switch билдит телегу с нуля.

я недавно nixos пользуюсь, мб я в конфигах чего нибудь напутал.

**Comment by kaeeraa** [comment]
кеш вроде бы существует, а вроде бы и нет, пытаюсь понять - почему так

**Comment by s0me1newithhand7s** [comment]
случалось и случается в никспкгс, надо копнуть в анстаб

**Comment by kaeeraa** [comment]
обновил источник кеша, теперь работает идеально
