### ISSUE TITLE
ayugram-desktop: not work with home manager

### ISSUE THREAD

**Issue by s0me1newithhand7s** [kaeeraa/ayugram-desktop#14]
yk the drill;

basically, internal test showed me that this flake wont work with `home-manager`, so i'll try to:

1. Investigate issue 
2. Find way to solve 
3. Test and release.

for now, folks..
..don't use it with hm.

<p align="right"> - hand7s</p>

**Comment by kaeeraa** [comment]
@s0me1newithhand7s if u need the hard way for your life - telegram forks is ur choice

**Comment by s0me1newithhand7s** [comment]
> @s0me1newithhand7s if u need the hard way for your life - telegram forks is ur choice

xdxd

**Comment by s0me1newithhand7s** [comment]
ok, fixed with new flake (partianlly)
