### ISSUE TITLE
Не собирается AyuGram 5.4.1

### ISSUE THREAD

**Issue by luckusmi** [kaeeraa/ayugram-desktop#2]
При обновление Home-manager (там прописан ayugram) он валится в ошибку. Прописивание в Nix, нечего хорошо не даёт.
![изображение](https://github.com/user-attachments/assets/c94a3cfb-d564-409e-9763-aa7492f0408b)
вот фулл ошибка
> https://pastebin.com/pKPA8Q8q

nix-info -m                                                                                               
>  system: `"x86_64-linux"`
> host os: `Linux 6.6.47, NixOS, 24.11 (Vicuna), 24.11.20240821.c374d94`
> multi-user?: `yes`
> sandbox: `yes`
> version: `nix-env (Nix) 2.18.5`
> nixpkgs: `/nix/store/j8pbrsb3nybdap3hhg9kw0ffqd4rlbx6-source`

home-manager/home.nix
> { inputs, config, lib, pkgs, ...}:
>  home.packages = with pkgs; [
>   inputs.ayugram-desktop.packages.${pkgs.system}.default
>  ];
> 
flake.nix
> inputs = {
>    ayugram-desktop = {
>      url = "git+https://github.com/kaeeraa/ayugram-desktop?submodules=1";
>    };
> };
> outputs = { self, ayugram-desktop, ...}@inputs:

**Comment by yahshield** [comment]
Скоро мы вам ответим, ожидайте пожалуйста
![image psd (3)](https://github.com/user-attachments/assets/dc25a3d9-4f15-4b9d-8fa5-bf27f3bc8683)

**Comment by kaeeraa** [comment]
Исправлено, попробуйте снова, так же сейчас имеются [проблемы с кешем](https://github.com/kaeeraa/ayugram-desktop/issues/1)

**Comment by kaeeraa** [comment]
Пофикшено, так же сейчас имеются [проблемы с кешем](https://github.com/kaeeraa/ayugram-desktop/issues/1)

**Comment by s0me1newithhand7s** [comment]
это,
видимо баг касается самих nixpkgs и/или tgd внутри, ибо ошибку фиксят патчем (тот же _64gram)
мой ишшуй (закрыт) посмотри

**Comment by luckusmi** [comment]
В этоге, вчера собрал ayugram. Но пришлось изменить флейк  с этого
```
inputs = {
 ayugram-desktop = {
  url = "git+https://github.com/kaeeraa/ayugram-desktop?submodules=1";
  };
};
outputs = { self, ayugram-desktop, ...}@inputs:
```
На это 
```
inputs = {
  ayugram-desktop = {
    url = "github:kaeeraa/ayugram-desktop/master";
  };
};
outputs = { self, ayugram-desktop, ...}@inputs:
```
C этими опциями он собирается :)

**Comment by kaeeraa** [comment]
раньше основной веткой был релиз, а сейчас мастер, поэтому по прошлой ссылке тоже будет работать

**Comment by s0me1newithhand7s** [comment]
> но либы и у меня не работают, надо пересмотреть зависимости

можно потянуть tgd из nixpkgs-master

**Comment by kaeeraa** [comment]
можете снова попробовать собрать? если есть время конечно, ибо кеша всё еще нету

**Comment by luckusmi** [comment]
пересобрал, такая-же ошибка.  
```
ayugram-desktop: error while loading shared libraries: libXtst.so.6: cannot open shared object file: No such file or directory
```

**Comment by dasehak** [comment]
> пересобрал, такая-же ошибка.
> 
> ```
> ayugram-desktop: error while loading shared libraries: libXtst.so.6: cannot open shared object file: No such file or directory
> ```

у меня то же самое

**Comment by kaeeraa** [comment]
в данный момент вы можете установить аюграм прошлой версии, просто замените `github:kaeeraa/ayugram-desktop` на `https://github.com/kaeeraa/ayugram-desktop/archive/refs/tags/ayugram-v5.2.2-v0.0.2.tar.gz`

**Comment by kaeeraa** [comment]
он будет сто процентов работать

**Comment by kaeeraa** [comment]
upd: релизнул новую версию в которой это пофикшено (с рабочим кешем!)
