### ISSUE TITLE
Trouble updating to v5.4.1

### ISSUE THREAD

**Issue by kaeeraa** [kaeeraa/ayugram-desktop#3]
error: builder for '/nix/store/nh74fkjgyc2nrzp3sw8w8dzzr1h4zmfy-ayugram-desktop-5.4.1.drv' failed with exit code 1;
       last 25 log lines:
       >                  from /build/source/Telegram/ThirdParty/tgcalls/tgcalls/ChannelManager.cpp:1:
       > /nix/store/wl7xs26116sswgw18pnc3yw9r5gxr6hx-gcc-13.3.0/include/c++/13.3.0/bits/unique_ptr.h: In instantiation of 'std::__detail::__unique_ptr_t<_Tp> std::make_unique(_Args&& ...) [with _Tp = cricket::VoiceChannel; _Args = {rtc::Thread* const&, rtc::Thread* const&, rtc::Thread* const&, int, int, const __cxx11::basic_string<char, char_traits<char>, allocator<char> >&, bool&, const webrtc::CryptoOptions&, rtc::UniqueRandomIdGenerator*}; __detail::__unique_ptr_t<_Tp> = __detail::__unique_ptr_t<cricket::VoiceChannel>]':
       > /build/source/Telegram/ThirdParty/tgcalls/tgcalls/ChannelManager.cpp:83:63:   required from here
       > /nix/store/wl7xs26116sswgw18pnc3yw9r5gxr6hx-gcc-13.3.0/include/c++/13.3.0/bits/unique_ptr.h:1070:30: error: no matching function for call to 'cricket::VoiceChannel::VoiceChannel(rtc::Thread* const&, rtc::Thread* const&, rtc::Thread* const&, int, int, const std::__cxx11::basic_string<char>&, bool&, const webrtc::CryptoOptions&, rtc::UniqueRandomIdGenerator*)'
       >  1070 |     { return unique_ptr<_Tp>(new _Tp(std::forward<_Args>(__args)...)); }
       >       |                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
       > In file included from /build/source/Telegram/ThirdParty/tgcalls/tgcalls/ChannelManager.h:16:
       > /nix/store/42253ba1qwvd8yp25siqphjfh16zvpyh-tg_owt-unstable-2023-12-21-dev/include/tg_owt/pc/channel.h:360:3: note: candidate: 'cricket::VoiceChannel::VoiceChannel(rtc::Thread*, rtc::Thread*, rtc::Thread*, std::unique_ptr<cricket::VoiceMediaChannel>, absl::lts_20240722::string_view, bool, webrtc::CryptoOptions, rtc::UniqueRandomIdGenerator*)'
       >   360 |   VoiceChannel(rtc::Thread* worker_thread,
       >       |   ^~~~~~~~~~~~
       > /nix/store/42253ba1qwvd8yp25siqphjfh16zvpyh-tg_owt-unstable-2023-12-21-dev/include/tg_owt/pc/channel.h:360:3: note:   candidate expects 8 arguments, 9 provided
       > /nix/store/wl7xs26116sswgw18pnc3yw9r5gxr6hx-gcc-13.3.0/include/c++/13.3.0/bits/unique_ptr.h: In instantiation of 'std::__detail::__unique_ptr_t<_Tp> std::make_unique(_Args&& ...) [with _Tp = cricket::VideoChannel; _Args = {rtc::Thread* const&, rtc::Thread* const&, rtc::Thread* const&, int, int, const __cxx11::basic_string<char, char_traits<char>, allocator<char> >&, bool&, const webrtc::CryptoOptions&, rtc::UniqueRandomIdGenerator*}; __detail::__unique_ptr_t<_Tp> = __detail::__unique_ptr_t<cricket::VideoChannel>]':
       > /build/source/Telegram/ThirdParty/tgcalls/tgcalls/ChannelManager.cpp:131:63:   required from here
       > /nix/store/wl7xs26116sswgw18pnc3yw9r5gxr6hx-gcc-13.3.0/include/c++/13.3.0/bits/unique_ptr.h:1070:30: error: no matching function for call to 'cricket::VideoChannel::VideoChannel(rtc::Thread* const&, rtc::Thread* const&, rtc::Thread* const&, int, int, const std::__cxx11::basic_string<char>&, bool&, const webrtc::CryptoOptions&, rtc::UniqueRandomIdGenerator*)'
       >  1070 |     { return unique_ptr<_Tp>(new _Tp(std::forward<_Args>(__args)...)); }
       >       |                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
       > /nix/store/42253ba1qwvd8yp25siqphjfh16zvpyh-tg_owt-unstable-2023-12-21-dev/include/tg_owt/pc/channel.h:406:3: note: candidate: 'cricket::VideoChannel::VideoChannel(rtc::Thread*, rtc::Thread*, rtc::Thread*, std::unique_ptr<cricket::VideoMediaChannel>, absl::lts_20240722::string_view, bool, webrtc::CryptoOptions, rtc::UniqueRandomIdGenerator*)'
       >   406 |   VideoChannel(rtc::Thread* worker_thread,
       >       |   ^~~~~~~~~~~~
       > /nix/store/42253ba1qwvd8yp25siqphjfh16zvpyh-tg_owt-unstable-2023-12-21-dev/include/tg_owt/pc/channel.h:406:3: note:   candidate expects 8 arguments, 9 provided
       > At global scope:
       > cc1plus: note: unrecognized command-line option '-Wno-unqualified-std-cast-call' may have been intended to silence earlier diagnostics
       > cc1plus: note: unrecognized command-line option '-Wno-ambiguous-reversed-operator' may have been intended to silence earlier diagnostics
       > cc1plus: note: unrecognized command-line option '-Wno-deprecated-volatile' may have been intended to silence earlier diagnostics
       > ninja: build stopped: subcommand failed.

**Comment by s0me1newithhand7s** [comment]
got same with:
```Nix
{ lib
, stdenv
, fetchFromGitHub
, telegram-desktop
, nix-update-script
}: 

telegram-desktop.overrideAttrs (old: rec {
  pname = "AyuGramDesktop";
  version = "5.4.1";

  src = fetchFromGitHub {
    owner = "AyuGram";
    repo = "${pname}";
    rev = "v${version}";

    fetchSubmodules = true;
    hash = "sha256-7KmXA3EDlCszoUfQZg3UsKvfRCENy/KLxiE08J9COJ8=";
  };

 cmakeFlags = (old.cmakeFlags or []) ++ [
    (lib.cmakeBool "disable_autoupdate" true)
  ];

  passthru.updateScript = nix-update-script {};

  meta = with lib; {
    description = "Desktop Telegram client with good customization and Ghost mode.";
    license = licenses.gpl3Only;
    platforms = platforms.all;
    homepage = "https://https://github.com/AyuGram/AyuGramDesktop";
    changelog = "https://https://github.com/AyuGram/AyuGramDesktop/releases/tag/v${version}";
    maintainers = with maintainers; [ s0me1newithhand7s ];
    mainProgram = "ayugram-desktop";
    broken = stdenv.isDarwin;
  };
})
```

there is `fetchpatch` in [_64gram](https://github.com/NixOS/nixpkgs/pull/335448) (and maybe for materialgram) in nixpkgs, so maybe it will helpout.
